### ISSUE TITLE
Monitoring is not showing statistics graphs

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#1]
...Copied from [Ignite Jira OF-1656](https://issues.igniterealtime.org/browse/OF-1656)...

When you go to Statistics page of Monitoring plugin it shows missing images for graphs. This was ok with 4.2.3 version. It is an upgrade from 4.2.3 version to 4.3.0 beta.

![of430beta-stats](https://user-images.githubusercontent.com/210858/50695168-855d3280-1001-11e9-8c53-70edb0d9ee42.PNG)

**Comment by wrooot** [comment]
Fixed with https://github.com/igniterealtime/openfire-monitoring-plugin/commit/762144dbc9e9243831926579e9d529d915263ce3

**Comment by wrooot** [comment]
1.7.0 release
