### ISSUE TITLE
Monitoring plugin should store messages asynchronously

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#15]
...Migrated from [Ignite Jira OF-1148](https://issues.igniterealtime.org/browse/OF-1148)...

When the monitoring plugin stores a message in the database, it is probably not needed that the delivery of the original message happens only after the database operation succeeds. This delays message delivery when the database is under load.

**Comment by guusdk** [comment]
This issue has been made obsolete by https://issues.igniterealtime.org/browse/OF-1487 and https://issues.igniterealtime.org/browse/OF-1200, which both were fixed in v1.5.0
