### ISSUE TITLE
Migrate JiveGlobal properties to SystemProperty values

### ISSUE THREAD

**Issue by Fishbowler** [igniterealtime/openfire-monitoring-plugin#163]
Monitoring plugin uses old Jive Globals everywhere.
Previously https://igniterealtime.atlassian.net/browse/OF-1964 prevented migration, but that's gone now.
With SystemProperty, we'll see all properties exposed in the Admin Console with good descriptions.

**Comment by guusdk** [comment]
@Fishbowler this issue seems to be linked to form a couple of commits, but I don't think there's a PR for those. Can you create one?

**Comment by Fishbowler** [comment]
https://github.com/igniterealtime/openfire-monitoring-plugin/pull/164
