### ISSUE TITLE
how to load chat history on client ?

### ISSUE THREAD

**Issue by maobiwen** [igniterealtime/openfire-monitoring-plugin#181]
First , Thank you for open source . my english is just soso  ,sorry

I want load chat history on client ,such as web client .
I think I need a  http-service to load chat history and the http-service must can be verify user authentication ，so ,if this plugin can do  it ? if it can't ,which one works?

**Comment by gjaekel** [comment]
Dear maobiwen,
may you please describe your usecase, first? Write down what we call an User Story: What's the purpose? Is this to be used by an arbitrary user, for the administrator or for a batch job?

At the end, all customer data is stored in the database. As an extreme, on may write an complete independent program to retrieve what every you can thing of from here.

**Comment by guusdk** [comment]
This issue tracker is intended to be used to track feature requests and bugs in the software. It is not intended as a way to ask for help. Please do not create issues if you're looking for advise or help.

You can seek help from the Ignite Realtime Community in various ways. Typically, asking questions in https://discourse.igniterealtime.org/ is a good start.
