### ISSUE TITLE
how to get chat archive with strophe?

### ISSUE THREAD

**Issue by maobiwen** [igniterealtime/openfire-monitoring-plugin#182]
I want get two people chat archive ,how can I do it with strophe.min.js?
I have run the monitoring plugin and much message in table ofMessageArchive

**Comment by Fishbowler** [comment]
Looks like you need this: https://github.com/strophe/strophejs-plugin-mam

**Comment by maobiwen** [comment]
> Looks like you need this: https://github.com/strophe/strophejs-plugin-mam

Yes,it is what I want . I had load chat archive success ,Thank you very much .
but ,I dont konw how to filter archive,I just can load all the message from one body with other body.
I want one page by one page ,20 rows a page to load

**Comment by maobiwen** [comment]
I solved it ,thank you 

js code like this    

 console.log("开始获取");
        connection.mam.query("jersey@192.168.2.222", {
            "with": "maobiwen1@192.168.2.222",
            "start": "2021-03-24T00:00:01Z",
            "end": "2021-03-24T23:59:59Z",
            onMessage: function (message) {
                console.log("Message from ", $(message).find("forwarded message").attr("from"),
                    ": ", $(message).find("forwarded message body").text());
                return true;
            },
            onComplete: function (response) {
                console.log("Got all the messages");
            }
        });


xml like this 

<?xml version="1.0" encoding="utf-8"?>

<body xmlns="http://jabber.org/protocol/httpbind" rid="1691702197" sid="6r5cq2060h">
  <iq xmlns="jabber:client" type="set" to="jersey@192.168.2.222" id="3:sendIQ">
    <query xmlns="urn:xmpp:mam:2">
      <x xmlns="jabber:x:data" type="submit">
        <field var="FORM_TYPE" type="hidden">
          <value>urn:xmpp:mam:2</value>
        </field>
        <field var="with">
          <value>maobiwen1@192.168.2.222</value>
        </field>
        <field var="start">
          <value>2021-03-24T00:00:01Z</value>
        </field>
        <field var="end">
          <value>2021-03-24T23:59:59Z</value>
        </field>
      </x>
      <set xmlns="http://jabber.org/protocol/rsm"></set>
    </query>
  </iq>
</body>

**Comment by maobiwen** [comment]
> Looks like you need this: https://github.com/strophe/strophejs-plugin-mam

I think I have got new problem。
I want load chat archive page by page ,20 rows one pay ,but when I use  'after-id' field,the server gime me a error response ,error like this :Unsupported field(s): after-id
why?
my request xml is :
`<?xml version="1.0" encoding="utf-8"?>

<body xmlns="http://jabber.org/protocol/httpbind" rid="2045460520" sid="9fhiqeze0w">
  <iq xmlns="jabber:client" type="set" to="jersey@192.168.2.222" id="8303:sendIQ">
    <query xmlns="urn:xmpp:mam:2">
      <x xmlns="jabber:x:data" type="submit">
        <field var="FORM_TYPE" type="hidden">
          <value>urn:xmpp:mam:2</value>
        </field>
        <field var="with">
          <value>maobiwen1@192.168.2.222</value>
        </field>
        <field var="after-id">
          <value>220</value>
        </field>
      </x>
      <set xmlns="http://jabber.org/protocol/rsm"></set>
    </query>
  </iq>
</body>`

**Comment by guusdk** [comment]
This issue tracker is intended to be used to track feature requests and bugs in the software. It is not intended as a way to ask for help. Please do not create issues if you're looking for advise or help.

You can seek help from the Ignite Realtime Community in various ways. Typically, asking questions in https://discourse.igniterealtime.org/ is a good start.
