### ISSUE TITLE
monitoring plugin miss message，it is a bug ,please fix it,thank you

### ISSUE THREAD

**Issue by maobiwen** [igniterealtime/openfire-monitoring-plugin#183]
I found that ,sometimes ,I send message by strophe.min.js ,message From A to B  ，I logined B by spark client，B had receive the message,but I can't found the message on table  'ofMessageArchive' ,Why? How can I fix this bug?

**Comment by guusdk** [comment]
You are basically asking: "it is sometimes not working as I expect it. Why?" Without more information, it is impossible to tell. 

There are plenty scenarios in which messages do not show up (immediately) in that database table (database writes are buffered for performance, the monitoring plugin has been configured to not capture that particular type of message, the chat room in which the message has been exchanged has message archiving disabled, the message is of a type that's ignored, etc, etc).

From the description that you're providing, I'm thinking it's as likely that you need help working with the product, as that it is that you've actually found a bug in the monitoring plugin. In any case, there's not enough information in here to be able for us to do anything. I'm closing this issue.

You can seek help in using our projects from the Ignite Realtime Community in various ways. Typically, asking questions in https://discourse.igniterealtime.org/ is a good start. I'm closing this issue.
