### ISSUE TITLE
Remove references to deprecated logger methods

### ISSUE THREAD

**Issue by evdherberg** [igniterealtime/openfire-monitoring-plugin#200]
In OF-1840 many deprecated methods were removed from the `org.jivesoftware.util.Log` class. The monitoring plugin still uses some of these methods, and will not compile against newer OF core versions. These references need to be removed.

**Comment by Beat-YT** [comment]
what are we supposed to use now..

**Comment by guusdk** [comment]
As an end-user, this change should not affect you. As a developer, you can use the `Logger` implementation that is part of the slf4j project. That dependency is provided by Openfire.
