### ISSUE TITLE
Message history display in admin console remains empty

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-monitoring-plugin#245]
In the 2.4.0, admin console users cannot look at the content of an archived chat. The chat can be selected, but where the transcript should be shown, nothing is displayed. This is an apparent javascript problem, as this is logged in the browser console: 

```
archive-search.jsp:10 Uncaught ReferenceError: xmlHttp is not defined
    at xhr.onload (archive-search.jsp:10:37)
xhr.onload @ archive-search.jsp:10
load (async)
showConversation @ archive-search.jsp:8
onclick @ archive-search.jsp?participant1=Any&participant2=Any&startDate=Any&endDate=Any&keywords=&submitForm=Search&start=&range=&parseRange=:701
```

**Comment by guusdk** [comment]
First reported here: https://discourse.igniterealtime.org/t/monitoring-plugin-2-4-0-issue-viewing-details-of-conversation

**Comment by WillGasperi** [comment]
Same here, any resolution?

**Comment by akrherz** [comment]
gonna likely do a 2.4.1 release today with this fixed, standby!
