### ISSUE TITLE
Fix Maven build

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-monitoring-plugin#29]
To build plugins for Openfire 4.3.0 pom.xml should include repositories tags pointing to Archiva. If plugin has pages in Admin Console, web.xml should also be added.

For references:
https://github.com/igniterealtime/openfire-clientControl-plugin/pull/11

**Comment by amishmm** [comment]
I am not able to build plugin either. "mvn verify" immediately gives:

> [INFO] Scanning for projects...
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-resolvable parent POM for org.igniterealtime.openfire.plugins:monitoring:1.7.0: Failure to find org.igniterealtime.openfire:plugins:pom:4.3.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]

I followed the link given above and added repository lines to pom.xml and it worked

Please fix this bug.

**Comment by guusdk** [comment]
Thank you for supplying the fix in #30 !
