### ISSUE TITLE
java.sql.BatchUpdateException: Invalid column name ‘messageID’

### ISSUE THREAD

**Issue by promiselaoliu** [igniterealtime/openfire-monitoring-plugin#32]
Hi Experts,

I found an unexpected error message in our embedded Openfire, after upgrading to 4.3.1.
The error is about the ConversationManager in the monitoring plugin 1.7.0.
[2019.03.06 10:34:33 org.jivesoftware.openfire.archive.ConversationManager - Unable to archive message data!

java.sql.BatchUpdateException: Invalid column name ‘messageID’.

at net.sourceforge.jtds.jdbc.JtdsStatement.executeBatch(JtdsStatement.java:1069) ~[jtds-1.3.1.jar:1.3.1]
…
]

Root cause:
The two columns (messageID, sentDate) are there when creating the table ofMessageArchive, but are not there when upgrading it.

Solution:
In src\database\upgrade\4*.sql, alter table to add these two columns.
For example, in SQL Server add the below statement as the first line,
ALTER TABLE ofMessageArchive ADD
messageID BIGINT,
stanza NVARCHAR(MAX);

Thanks,

**Comment by guusdk** [comment]
From your comments, I think that the issue is specific to MSSQL. I can, however, find a database update script (number three) that adds the messageID column. 

Exactly how do you reproduce this problem? What version of the plugin did you originally have installed?

**Comment by promiselaoliu** [comment]
Oh yes, the database update script (number three) already adds the messageID column.
Sorry, maybe we have used an old versioned and customized plugin.

**Comment by guusdk** [comment]
Okay, thanks for the feedback. I'm not claiming that there's definitely not a problem here, but given your comment, I'm not going to spend the time to investigate this further at this time. Please re-open if this warrants further investigation!
