### ISSUE TITLE
Allow (optional) public exposure of archives

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-monitoring-plugin#35]
The monitoring plugin should allow certain or all archives to be made available through a HTML-based front-end.

**Comment by guusdk** [comment]
We can take hints from Prosody, that generates a public archive like this: http://logs.xmpp.org/

**Comment by marclaporte** [comment]
Related: https://wikisuite.org/item46-Openfire-XMPP-chat-and-video-logs-to-be-searchable-and-accessible-to-Tiki
