### ISSUE TITLE
It seems we are losing MUC messages with converse 5.0.1

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-monitoring-plugin#52]
I am passing on to the monitoring plugin, an issue that was registered with Pade about missing MUC chat messages. I have seen the issue as well, but unable to reproduce locally. Openfire definitely routes it to all conversation participants, but nothing shows in the archive history

See https://github.com/igniterealtime/Pade/issues/198

**Comment by guusdk** [comment]
If things do not show up in the (admin-console-based) interface of the Monitoring plugin, then it is most likely that the original message never arrived from the client to the server. This would, however, make it impossible for other people to see the message, which does happen according to your description.

In the 4.4.x branch (active on WikiSuite where I think you've observed this), we're suffering from a s2s issue that can could cause this, if the sending entity is joined over s2s.

**Comment by deleolajide** [comment]
> if the sending entity is joined over s2s.

I considered that, but the reported user is a local user and I was connected locally when I also experienced it. I intend to capture Openfire logs next time it happens

**Comment by guusdk** [comment]
My next guess would be some kind of database error that pops up when trying to save or retrieve messages. I've seen this before - I think it was caused by an XML parser that was causing an issue.

**Comment by deleolajide** [comment]
I remember that, but not sure if there were any XML type characters in the post. Lets see what the openfire logs throw up next time it happens ;-)

**Comment by guusdk** [comment]
Significant changes have gone into both Openfire as well as Converse. It's unlikely that we'll work on this particular issue, unless we find an indication that something is still amiss. If so, lets re-open or create a new issue.
