### ISSUE TITLE
Some private chat history  is better than none.

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-monitoring-plugin#56]
Private chat history via MAM is not working.  My investigation found that the following code is failing. It returns feature not implemented to XMPP client (conversejs)

```
        this.iqDispatcher = new AbstractIQHandler(iqDispatcherName, null, iqDispatcherNamespace) {
            public IQ handleIQ(IQ packet) throws UnauthorizedException {
                if (!MonitoringPlugin.getInstance().isEnabled()) {
                    return error(packet,
                            PacketError.Condition.feature_not_implemented);
                }

                final IQHandler iqHandler = element2Handlers.get(packet
                        .getChildElement().getName());
                if (iqHandler != null) {
                    return iqHandler.handleIQ(packet);
                } else {
                    return error(packet,
                            PacketError.Condition.feature_not_implemented);
                }
            }
        };
```
I found that I can replace this with the following hack to get at least MAM:2 private chat

```
        this.iqDispatcher = new IQQueryHandler2();
```

**Comment by deleolajide** [comment]
This [commit ](https://github.com/igniterealtime/openfire-monitoring-plugin/commit/36d8eb3105aaad93d47e294419b3b67ccb818a3d) is not working reliably.  It works on my dev PC with 1.8.0_144 Oracle Corporation -- Java HotSpot(TM) 64-Bit Server VM, but does not work on my production server with 1.8.0_222 Oracle Corporation -- OpenJDK 64-Bit Server VM

I had to revert back to 

```
   this.iqDispatcher = new IQQueryHandler2();
```
To get a reliable result

**Comment by guusdk** [comment]
That's surprising. It's the change in key type (from String to QName) that's causing you issues? What issues are those?

**Comment by deleolajide** [comment]
It returns feature not implemented to XMPP client (conversejs). The change seems to fail on all my linux servers so far. Only works with my windows dev pc

**Comment by mightymop** [comment]
Why not using the xml namespace (xmlns) to identify the correct mam type?

**Comment by mightymop** [comment]
i checked it again, and it seems to work under my linux dev env with guusdk's commit
