### ISSUE TITLE
Typo/copy&paste error in code > SQL Exception

### ISSUE THREAD

**Issue by mightymop** [igniterealtime/openfire-monitoring-plugin#69]
fix: https://github.com/igniterealtime/openfire-monitoring-plugin/pull/68

**Comment by guusdk** [comment]
The bug that's tracked by this issue relates to using the wrong indexes for parameters when using a prepared statement in `src/java/org/jivesoftware/openfire/archive/ConversationManager.java`. I agree that this looks like an obvious copy/paste bug.

Thanks for your work on this! Your fix has been merged, and will be part of the next release.
