### ISSUE TITLE
Monitoring plugin does not retrieve last page of chat history when <before> is empty

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-monitoring-plugin#76]
Converse sends an emtpy <before> on the first MAM request. Monitoring plugin assumes empty <before> is missing <before>. With no <before> or <after> paging set, it sets the database offset to zero and fetches the first <max> records it can find. 

XEP-0059 does not say anything about what should happen when <before> is empty. It should interpret this as "give me all last <max> messages"

**Comment by guusdk** [comment]
This behavior is specified in this section of the RSM XEP: https://xmpp.org/extensions/xep-0059.html#last
