### ISSUE TITLE
Return item-not-found when using unrecognized references in RSM

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-monitoring-plugin#79]
As found by @fishbowler:

 XEP-0313: 
> If the UID contained within an <after> or <before> element is not present in the archive, the server MUST return an item-not-found error in response to the query.

For a request of a small set:

    <set xmlns='http://jabber.org/protocol/rsm'>
        <max>1</max>
        <after>99999</after>
    </set>

Result

    <fin xmlns="urn:xmpp:mam:2" queryid="00003">
        <set xmlns="http://jabber.org/protocol/rsm"&gt;
            <count>0</count>
        </set>
    </fin>

I get a different result if I use <after>Potato</after>, but still not the item-not-found

**Comment by Fishbowler** [comment]
Fix in the referenced commit works for "99999" and "potato" ✅
