### ISSUE TITLE
Exception when search text contains special characters

### ISSUE THREAD

**Issue by annovanvliet** [igniterealtime/openfire-monitoring-plugin#91]
While testing 2.0.0.
When searching an Exception is thrown when searching with a filter text with columns (':') or ampersands ('&&') in it:

2020.01.30 13:47:07 WARN [message-archive-handler-12]: com.reucon.openfire.plugin.archive.impl.PaginatedMucMessageLuceneQuery - An exception occurred while trying to query the Lucene index to get messages from room org.jivesoftware.openfire.muc.spi.LocalMUCRoom@53f925d4.
org.apache.lucene.queryparser.classic.ParseException: Cannot parse '11:20:54': Encountered " ":" ": "" at line 1, column 5.

**Comment by guusdk** [comment]
This is reproduced with requests like these:

```
<iq id="juliet1" to="open_chat@conference.igniterealtime.org" type="set">
  <query xmlns="urn:xmpp:mam:2">
    <x type="submit" xmlns="jabber:x:data">
      <field type="hidden" var="FORM_TYPE">
        <value>urn:xmpp:mam:2</value>
      </field>
      <field var="withtext">
        <value>&amp;&amp;</value>
      </field>
    </x>
  </query>
</iq>


<iq id="juliet2" to="open_chat@conference.igniterealtime.org" type="set">
  <query xmlns="urn:xmpp:mam:2">
    <x type="submit" xmlns="jabber:x:data">
      <field type="hidden" var="FORM_TYPE">
        <value>urn:xmpp:mam:2</value>
      </field>
      <field var="withtext">
        <value>11:20:54</value>
      </field>
    </x>
  </query>
</iq>
```
